# Generated by Django 4.2.7 on 2023-11-23 22:52
    
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    # Define initial migration
    initial = True

    # Dependencies on previous migrations
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'), # Dependency on auth app migration
    ]

    # Operations to be performed during migration
    operations = [
        # Creating SensorData model
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), # Auto-generated primary key
                ('sensort', models.FloatField()), # Field for sensor reading
                ('servo_vertical', models.FloatField()), # Field for vertical servo reading
                ('secury_mode', models.BooleanField()), # Field indicating security mode
            ],
        ),
        # Creating UserEntity model
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)), # One-to-one relationship with default user model
                ('created_at', models.DateTimeField(auto_now_add=True)), # Automatically set to creation time
                ('updated_at', models.DateTimeField(auto_now=True)), # Automatically updated on every save
                ('email', models.EmailField(max_length=128, unique=True, validators=[django.core.validators.EmailValidator()])), # Unique email field with validation
            ],
        ),
    ]
